// <auto-generated />
using System;
using Linde.Persistence.Coaching;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Linde.Persistence.Coaching.Migrations
{
    [DbContext(typeof(CoachingDbContext))]
    [Migration("20231218180926_CatChecklist")]
    partial class CatChecklist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Linde.Domain.Coaching.ActivityAggregate.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ActivityId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CAT_ACTIVITIES", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.ChecklistAggregate.CatChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ChecklistId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CAT_CHECKLISTS", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.ChecklistAggregate.Entities.ChecklistsQuestions", b =>
                {
                    b.Property<Guid>("CatChecklistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CatChecklistId");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuestionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CatChecklistId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ASOC_CHECKLISTS_QUESTIONS", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.CountryAggregate.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CountryId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CAT_COUNTRY", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.DivisionAggregate.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DivisionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CAT_DIVISIONS", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Entities.Catalogs.Plant", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlantId");

                    b.Property<string>("Bu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Bu");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("City");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CountryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Division");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Municipality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Name");

                    b.Property<Guid>("PlantManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlantManagerId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("State");

                    b.Property<Guid>("SuperintendentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SuperintendentId");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("PlantId");

                    b.HasIndex("CountryId");

                    b.HasIndex("PlantManagerId");

                    b.HasIndex("SuperintendentId");

                    b.ToTable("CAT_PLANT", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Entities.Catalogs.RolePlant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "PlantId", "RoleId");

                    b.HasIndex("PlantId");

                    b.HasIndex("RoleId");

                    b.ToTable("ASOC_ROLE_PLANT", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.MenuAggregate.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MenuId");

                    b.Property<bool>("ContainsChildren")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PermissionId")
                        .IsUnique()
                        .HasFilter("[PermissionId] IS NOT NULL");

                    b.ToTable("TBL_MENUS", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Notifications.TblNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("TypeNotification")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("NotificationId");

                    b.ToTable("TBL_NOTIFICATIONS", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.PermissionAggregate.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PermissionId");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CAT_PERMISSION", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Questions.CatQuestions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuestionId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CAT_QUESTIONS", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Questionsaggregate.Entities.QuestionsActivities", b =>
                {
                    b.Property<Guid>("CatQuestionsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CatQuestionsId");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ActivityId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CatQuestionsId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ASOC_QUESTIONS_ACTIVITIES", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.RoleAggregate.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CAT_ROLE", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.UserAggreagate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lockout")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeUser")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("CAT_USER", "dbo");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Views.VwEmpleado", b =>
                {
                    b.Property<string>("Bu")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("BU");

                    b.Property<decimal?>("CIA")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CIA");

                    b.Property<string>("CodeCountry")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Pais");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstLastName")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ApellidoPaterno");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NombreEmpleado");

                    b.Property<string>("NameComplete")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal?>("NoAutorizationEmployee")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NO_EMP_AUTORIZA");

                    b.Property<decimal?>("NoEmPloyee")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NO_EMP");

                    b.Property<string>("NoSupervisor")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NoEmpleadoJefe");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ApellidoMaterno");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Jefe");

                    b.Property<string>("User")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("USUARIO");

                    b.ToView("huemplea_arc");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.ChecklistAggregate.Entities.ChecklistsQuestions", b =>
                {
                    b.HasOne("Linde.Domain.Coaching.ChecklistAggregate.CatChecklist", "Checklists")
                        .WithMany("ChecklistsQuestions")
                        .HasForeignKey("CatChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Linde.Domain.Coaching.Questions.CatQuestions", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklists");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Entities.Catalogs.Plant", b =>
                {
                    b.HasOne("Linde.Domain.Coaching.CountryAggregate.Country", "Country")
                        .WithMany("Plants")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linde.Domain.Coaching.UserAggreagate.User", "UserManager")
                        .WithMany("PlantManager")
                        .HasForeignKey("PlantManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Linde.Domain.Coaching.UserAggreagate.User", "UserSuperIntendent")
                        .WithMany("PlantSuperIntendet")
                        .HasForeignKey("SuperintendentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("UserManager");

                    b.Navigation("UserSuperIntendent");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Entities.Catalogs.RolePlant", b =>
                {
                    b.HasOne("Linde.Domain.Coaching.Entities.Catalogs.Plant", "Plant")
                        .WithMany("RolePlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linde.Domain.Coaching.RoleAggregate.Role", "Role")
                        .WithMany("RolePlants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Linde.Domain.Coaching.UserAggreagate.User", "User")
                        .WithMany("RolePlants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.MenuAggregate.Menu", b =>
                {
                    b.HasOne("Linde.Domain.Coaching.MenuAggregate.Menu", "Attribute")
                        .WithMany("Attributes")
                        .HasForeignKey("ParentId");

                    b.HasOne("Linde.Domain.Coaching.PermissionAggregate.Permission", "Permissions")
                        .WithOne("Menu")
                        .HasForeignKey("Linde.Domain.Coaching.MenuAggregate.Menu", "PermissionId");

                    b.Navigation("Attribute");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Questionsaggregate.Entities.QuestionsActivities", b =>
                {
                    b.HasOne("Linde.Domain.Coaching.ActivityAggregate.Activity", "Activity")
                        .WithMany("QuestionsActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Linde.Domain.Coaching.Questions.CatQuestions", "Questions")
                        .WithMany("QuestionsActivities")
                        .HasForeignKey("CatQuestionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.RoleAggregate.Role", b =>
                {
                    b.OwnsMany("Linde.Domain.Coaching.RoleAggregate.Entities.RolePermission", "PermissionItems", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RoleId", "PermissionId");

                            b1.HasIndex("PermissionId");

                            b1.ToTable("ASOC_ROLE_PERMISSION", "dbo");

                            b1.HasOne("Linde.Domain.Coaching.PermissionAggregate.Permission", "Permission")
                                .WithMany()
                                .HasForeignKey("PermissionId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("RoleId");

                            b1.Navigation("Permission");
                        });

                    b.Navigation("PermissionItems");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.UserAggreagate.User", b =>
                {
                    b.OwnsMany("Linde.Domain.Coaching.UserAggreagate.Entities.UserCountry", "CountryItems", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserId", "CountryId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("ASOC_USER_COUNTRY", "dbo");

                            b1.HasOne("Linde.Domain.Coaching.CountryAggregate.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.Navigation("Country");
                        });

                    b.OwnsMany("Linde.Domain.Coaching.UserAggreagate.Entities.UserRole", "RoleItems", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserId", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.ToTable("ASOC_USER_ROLE", "dbo");

                            b1.HasOne("Linde.Domain.Coaching.RoleAggregate.Role", "Role")
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.Navigation("Role");
                        });

                    b.Navigation("CountryItems");

                    b.Navigation("RoleItems");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.ActivityAggregate.Activity", b =>
                {
                    b.Navigation("QuestionsActivities");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.ChecklistAggregate.CatChecklist", b =>
                {
                    b.Navigation("ChecklistsQuestions");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.CountryAggregate.Country", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Entities.Catalogs.Plant", b =>
                {
                    b.Navigation("RolePlants");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.MenuAggregate.Menu", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.PermissionAggregate.Permission", b =>
                {
                    b.Navigation("Menu")
                        .IsRequired();
                });

            modelBuilder.Entity("Linde.Domain.Coaching.Questions.CatQuestions", b =>
                {
                    b.Navigation("QuestionsActivities");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.RoleAggregate.Role", b =>
                {
                    b.Navigation("RolePlants");
                });

            modelBuilder.Entity("Linde.Domain.Coaching.UserAggreagate.User", b =>
                {
                    b.Navigation("PlantManager");

                    b.Navigation("PlantSuperIntendet");

                    b.Navigation("RolePlants");
                });
#pragma warning restore 612, 618
        }
    }
}
